# ─── User Ghostty Overrides ──────────────────────────────────────────
# This file is included at the end of slicker's ghostty config

# font-family = TX-02-Variable
# font-family = Iosevka Nerd Font
font-family = IoskeleyMonoNL Nerd Font
font-size = 14

custom-shader = ./shaders/cursor_warp.glsl
# custom-shader = ./shaders/water_ripple.glsl

# Utility
keybind = ctrl+o>r=unbind

macos-titlebar-style = native



# Pane splitting and navigation
# keybind = performable:ctrl+j=goto_split:bottom
# keybind = performable:ctrl+k=goto_split:up
# keybind = performable:ctrl+h=goto_split:left
# keybind = performable:ctrl+l=goto_split:right
# keybind = super+option+minus=new_split:down
# keybind = super+option+backslash=new_split:right
#
## Resize mode
keybind = ctrl+m=activate_key_table:resize
keybind = resize/
keybind = resize/h=resize_split:left,50
keybind = resize/j=resize_split:down,50
keybind = resize/k=resize_split:up,50
keybind = resize/l=resize_split:right,50
keybind = resize/catch_all=ignore
keybind = resize/escape=deactivate_key_table
keybind = resize/enter=deactivate_key_table
keybind = resize/q=deactivate_key_table
#
# keybind = super+shift+l=next_tab
# keybind = super+shift+t=new_tab
# keybind = super+shift+m=toggle_split_zoom
# keybind = super+shift+comma=move_tab:-1
# keybind = super+shift+period=move_tab:1
# keybind = super+shift+c=copy_to_clipboard
# keybind = super+shift+enter=new_split:auto
# keybind = super+shift+r=reload_config
# keybind = super+shift+h=previous_tab
# keybind = super+shift+v=paste_from_clipboard
#
# # Tabs
# keybind = ctrl+t>r=prompt_tab_title


## TMUX
keybind = super+option+minus=text:\x02\x22
keybind = super+j=text:\x02\x22
keybind = super+option+backslash=text:\x02\x25
keybind = super+shift+right_bracket=text:\x02\x6e
keybind = super+shift+left_bracket=text:\x02\x70
keybind = super+t=text:\x02\x63
keybind = super+x=text:\x02\x78
keybind = super+w=text:\x02\x78
keybind = super+comma=text:\x02\x2c
