# ─── User Ghostty Overrides ──────────────────────────────────────────
# This file is included at the end of slicker's ghostty config

# font-family = TX-02-Variable
font-family = Iosevka Nerd Font
font-size = 14

custom-shader = ./shaders/cursor_warp.glsl

# Utility
keybind = ctrl+o>r=unbind
