accent = "#88c0d0"
cursor = "#88c0d0"
foreground = "#5c6165"
background = "#ffffff"
selection_foreground = "#5c6165"
selection_background = "#e7f2f6"

color0 = "#1c1c1c"
color1 = "#cc6666"
color2 = "#bdb968"
color3 = "#f0c674"
color4 = "#81a2be"
color5 = "#b193ba"
color6 = "#7fb2c8"
color7 = "#c8ccd4"
color8 = "#636363"
color9 = "#a04041"
color10 = "#8b9440"
color11 = "#ec9c62"
color12 = "#5d7f9a"
color13 = "#82658c"
color14 = "#5e8d87"
color15 = "#ffffff"
