theme = "nord"
[editor]
mouse = true
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
A-k = "move_line_up"
A-j = "move_line_down"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
