require("items.apple")
require("items.spaces")
-- require("items.front_app")
require("items.workspace_apps")
require("items.calendar")
-- require("items.uname")
require("items.volume")
require("items.battery")
require("items.keyboard")
require("items.caffeinate")
require("items.tunnelblick")
require("items.mirrors")
require("items.media")
