# >>> theme colors (generated by bin/theme) >>>
[theme.custom]
accent = "{{ accent }}"
panel_bg = "{{ background }}"
sidebar_bg = "{{ background }}"
text = "{{ foreground }}"
subtext0 = "{{ color8 }}"
selection_bg = "{{ selection_background }}"
active_row_bg = "{{ selection_background }}"
red = "{{ color1 }}"
green = "{{ color2 }}"
yellow = "{{ color3 }}"
blue = "{{ color4 }}"
mauve = "{{ color5 }}"
teal = "{{ color6 }}"
# <<< theme colors <<<
