# >>> theme colors {{ mode }} (generated by bin/theme) >>>
[theme.custom.{{ mode }}]
accent = "{{ accent }}"
panel_bg = "{{ background }}"
sidebar_bg = "{{ background }}"
text = "{{ foreground }}"
subtext0 = "{{ mix60 }}"
selection_bg = "{{ surface }}"
active_row_bg = "{{ surface }}"
red = "{{ color1 }}"
green = "{{ color2 }}"
yellow = "{{ color3 }}"
blue = "{{ color4 }}"
mauve = "{{ color5 }}"
teal = "{{ color6 }}"
# <<< theme colors {{ mode }} <<<
