// Generated by `theme set` from themes/templates/quickshell-colors.qml.tpl.
// Symlinked into ~/.config/quickshell/Colors.qml, so shell.qml picks it up
// as a plain same-directory component.
import QtQuick

QtObject {
  readonly property color bg: "{{ background }}"
  readonly property color fg: "{{ foreground }}"
  readonly property color accent: "{{ accent }}"
  readonly property color muted: "{{ color8 }}"
  readonly property color sel: "{{ selection_background }}"
  readonly property color red: "{{ color1 }}"
  readonly property color green: "{{ color2 }}"
  readonly property color yellow: "{{ color3 }}"
}
