{
  "id": "dotfiles-{{ mode }}",
  "familyId": "dotfiles",
  "name": "Dotfiles {{ mode }}",
  "appearance": "{{ mode }}",
  "recommendedSurfaceTreatment": "opaque",
  "colors": {
    "background": "{{ background }}",
    "shell": "{{ mix3 }}",
    "raised": "{{ mix11 }}",
    "card": "{{ mix8 }}",
    "dialog": "{{ mix8 }}",
    "overlay": "{{ mix11 }}",
    "hover": "{{ tone }}1a",
    "active": "{{ highlight }}2e",
    "border": "{{ tone }}1f",
    "borderStrong": "{{ tone }}3a",
    "text": "{{ foreground }}",
    "textMuted": "{{ mix70 }}",
    "textFaint": "{{ mix50 }}",
    "solid": "{{ foreground }}",
    "onSolid": "{{ background }}",
    "danger": "{{ color1 }}",
    "dangerMuted": "{{ color1 }}",
    "warning": "{{ color3 }}",
    "warningMuted": "{{ color3 }}",
    "success": "{{ color2 }}",
    "successMuted": "{{ color2 }}",
    "input": "{{ mix8 }}",
    "cursor": "{{ foreground }}80",
    "diffAdd": "{{ color2 }}",
    "diffDelete": "{{ color1 }}",
    "diffHunk": "{{ highlight }}14"
  },
  "accent": {
    "primary": "{{ highlight }}",
    "strong": "{{ highlight }}",
    "wash": "{{ highlight }}38",
    "on": "{{ background }}",
    "selection": "{{ highlight }}59",
    "caret": "{{ highlight }}",
    "activity": "{{ highlight }}",
    "glyph": ["{{ color6 }}", "{{ highlight }}", "{{ color4 }}"]
  },
  "syntax": {
    "comment": "{{ color8 }}",
    "keyword": "{{ color5 }}",
    "macro": "{{ color5 }}",
    "operator": "{{ color5 }}",
    "variableSpecial": "{{ color5 }}",
    "string": "{{ color2 }}",
    "stringSpecial": "{{ color3 }}",
    "escape": "{{ color3 }}",
    "attribute": "{{ color3 }}",
    "number": "{{ color3 }}",
    "boolean": "{{ color3 }}",
    "constant": "{{ color3 }}",
    "type": "{{ color6 }}",
    "typeBuiltin": "{{ color6 }}",
    "constructor": "{{ color6 }}",
    "function": "{{ color4 }}",
    "functionBuiltin": "{{ color4 }}",
    "label": "{{ color4 }}",
    "property": "{{ color6 }}",
    "variable": "{{ foreground }}",
    "parameter": "{{ foreground }}",
    "punctuation": "{{ mix70 }}",
    "embedded": "{{ mix70 }}",
    "tag": "{{ color1 }}",
    "invalid": "{{ color1 }}"
  },
  "terminal": {
    "background": "{{ background }}",
    "foreground": "{{ foreground }}",
    "selection": "{{ tone }}30",
    "ansi": [
      "{{ color0 }}", "{{ color1 }}", "{{ color2 }}", "{{ color3 }}",
      "{{ color4 }}", "{{ color5 }}", "{{ color6 }}", "{{ color7 }}",
      "{{ color8 }}", "{{ color9 }}", "{{ color10 }}", "{{ color11 }}",
      "{{ color12 }}", "{{ color13 }}", "{{ color14 }}", "{{ color15 }}"
    ]
  },
  "source": {
    "format": "native",
    "url": "dotfiles",
    "revision": "local",
    "license": "User supplied",
    "assetHash": "sha256:dotfiles"
  }
}
