#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^Системные настройки$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" manage=off sticky=on
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Übersicht$" manage=off border=off

yabai -m rule --add app="^Google Chrome" space=^1
yabai -m rule --add app="^Firefox" space=^1
# yabai -m rule --add app="^Code" space=^2
yabai -m rule --add app="^Kitty" space=^2
yabai -m rule --add app="^Alacritty" space=^2
yabai -m rule --add app="^Slack" space=^3
yabai -m rule --add app="^Telegram" space=^3
yabai -m rule --add app="^Spotify" space=^4

yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label chat
yabai -m space 4 --label music
yabai -m space 5 --label term


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_border_radius         12
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
# yabai -m config window_shadow                float
yabai -m config window_border_blur           off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.1
yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.8
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff81A1C1
yabai -m config normal_window_border_color   0xff434C5E
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config window_animation_duration    0.1
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
# yabai -m config external_bar                 all:40:0
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

echo "yabai configuration loaded.."

#END
