
set -g status-style 'bg=default,fg=black' # transparent status bar

set -g window-status-format '#[fg=black,bg=default] #I #(pwd="#{pane_current_path}"; echo ${pwd####*/})  '
set -g window-status-current-format '#[fg=#{ACTIVE_COLOR},bold, bg=brightwhite] #I #(pwd="#{pane_current_path}"; echo ${pwd####*/})  '
